# Generated by Django 3.2.4 on 2021-06-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=11, null=True)),
                ('email', models.EmailField(max_length=320)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
